# Generated by Django 2.2.15 on 2020-08-27 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='test',
            field=models.OneToOneField(blank=True, default='FFFF', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='homepage_test', to='home.CustomText'),
        ),
    ]
