# Generated by Django 2.2.15 on 2020-08-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200827_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tests',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
